### ISSUE TITLE
Add Travis for build testing

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#133]
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions

**Comment by mattada** [comment]
But travis is so expensive for non open source projects.


Matt Adams
mattadams@factor1studios.com  |  twitter.com/mattada


*factor1*
factor1studios.com  |  twitter.com/factor1
602.334.4806 office  |  602.509.7553 mobile

**Comment by erwstout** [comment]
Travis would just be used for the development on Prelude.

**Comment by erwstout** [comment]
Currently the build process hangs at the prompt for file movement. Might want to try to find a way to let the prompt timeout to a NO.

**Comment by erwstout** [comment]
Integrated and working.
