### ISSUE TITLE
BrowserSync Cache Busting

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#141]
When using browsersync the cache can get in the way of the changes you just made. Might need to find a workaround while in dev, or perhaps change CSS and JS files to add a hash when built instead of a version number. Worth exploring.

**Comment by erwstout** [comment]
In `release/4.2.0` we upgraded BrowserSync to its latest version, we will test and see how that works before trying other measures.

**Comment by erwstout** [comment]
Is now live on master and released. Will watch performance.

**Comment by erwstout** [comment]
@mlpatt23 @nexpos has this still been a big issue for you?

**Comment by mlpatt23** [comment]
Not that I've noticed. I always work in an incognito mode, keep Local's dev mode on, and use a ".test" extension for my local sites; that combination seems to help

**Comment by erwstout** [comment]
Also worth noting that you can `disable cache` via dev tools while dev tools are open. @mlpatt23
