### ISSUE TITLE
Consider removing Font Awesome by default

### ISSUE THREAD

**Issue by mlpatt23** [factor1/prelude-wp#163]
A very early v5 script is located in `inc/enqueues.php`, and there is also the following line in `assets/js/src/theme.js`:

`window.FontAwesomeConfig = { searchPseudoElements: true };`

That line in particular seems to cause conflicts with other packages, possibly due to the amount of processing power it can take? 

Also, in `assets/scss/components/_social-menu.scss`, I think we should remove all styles from the `.menu-social ul li a` selector and just leave a blank line for now, since these can vary depending on what version of Font Awesome is used (webfont or svg).

**Comment by erwstout** [comment]
Removed in `v5.0.2` which has been published to npm
