### ISSUE TITLE
File paths for SVG images under assets/img folder are incorrect in compiled CSS

### ISSUE THREAD

**Issue by mlpatt23** [factor1/prelude-wp#178]
I am trying to use the `angle.svg` image under `assets/img` in my test project. It gets copied to the `dist` folder with a string saved in the file name: `angle.31eab241.svg`

![Screen Shot 2020-01-13 at 12 52 04 PM](https://user-images.githubusercontent.com/25210413/72287396-37134400-3604-11ea-8e5d-7289f36d7a46.png)

Here's a screenshot of the file tree:
![Screen Shot 2020-01-13 at 12 51 46 PM](https://user-images.githubusercontent.com/25210413/72287200-d3891680-3603-11ea-82e4-7f786e4b9e31.png)

When looking at the compiled styles on the front end of the site, it seems to be looking for `dist/dist/angle.31eab241.svg` instead of `dist/angle.31eab241.svg`:

![Screen Shot 2020-01-13 at 12 52 33 PM](https://user-images.githubusercontent.com/25210413/72287405-3c708e80-3604-11ea-9c3d-a58f648d4ee0.png)

![Screen Shot 2020-01-13 at 12 52 44 PM](https://user-images.githubusercontent.com/25210413/72287411-40041580-3604-11ea-8e5b-749fc55c2314.png)

**Comment by erwstout** [comment]
https://github.com/factor1/prelude-wp/pull/179
