### ISSUE TITLE
Graceful Error Handling

### ISSUE THREAD

**Issue by bebaps** [factor1/prelude-wp#50]
Right now the gulp build handles errors as it should but I think that it could be more graceful. Simple syntax errors stop compiling as expected but sometimes it is not made very clear of the error until you actually look at the terminal. And even then, if using a plugins default error messages it is not as apparent as it could be what the error is. I am aware of some gulp plugins and options that help to provide notifications of gulp errors, or help to format the error notices in terminal for ease of use. Will submit pull request soon with the plugins so you can see them.

**Comment by erwstout** [comment]
Feel free to roll this in whenever.

**Comment by bebaps** [comment]
I forgot all about this, I'll work on it today

**Comment by erwstout** [comment]
Thanks, Persky!
