### ISSUE TITLE
Change watch task to prevent double/triple style compiles

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#57]
Currently the watch task for styles appears like this:

`gulp.watch( styleFiles, ['styles']);`

Currently testing `gulp.watch( sassFiles, ['styles']);` in its place. 

In the end, Prelude would no longer watch `.css` files for changes, however `minify-css` is called with the `gulp styles` task which will still allow for compiling css changes.

**Comment by bebaps** [comment]
I am in favor of actually breaking up the tasks to be as specific as possible, one task to handle only one responsibility. I'll draft up a variation to show for feedback.

**Comment by erwstout** [comment]
I'd be interested in what you'd come up with, I'm not sure how we could break them up correctly. Just watching `gulp.watch( sassFiles, ['styles']);` is working like a charm.

**Comment by erwstout** [comment]
When I say correctly I think I meant differently

**Comment by erwstout** [comment]
Thanks, Persky! Rolled out in `3.2.0`
