### ISSUE TITLE
Page tile output

### ISSUE THREAD

**Issue by mattada** [factor1/prelude-wp#58]
Currently the WP4.1 method of registering the page title output in the functions has a poor final result. 

example:

> sitename.com – Page Array – Just another WordPress site

I think the default output of prelude should be:

> Site name - Page name

**Comment by mattada** [comment]
Current function on known site with the issue

`      // Add theme support for document Title tag
      add_theme_support( 'title-tag' );`

**Comment by mattada** [comment]
https://wordpress.org/support/topic/title_tag-causing-array-to-string-conversion-error

**Comment by mattada** [comment]
ACF option page registration is indeed the cuplrit here

BAD:
`  if ( function_exists( 'acf_add_options_page' ) ) {
    $page = acf_add_options_page(
      array(
        'page_title' => 'Theme Options',
        'menu_title' => 'Theme Options',
        'menu_slug'  => 'theme-options',
        'capability' => 'edit_posts',
        'redirect'   => false
      ) );
  }`


GOOD: 
`  if ( function_exists( 'acf_add_options_page' ) ) {
    $acfpage = acf_add_options_page(
      array(
        'page_title' => 'Theme Options',
        'menu_title' => 'Theme Options',
        'menu_slug'  => 'theme-options',
        'capability' => 'edit_posts',
        'redirect'   => false
      ) );
  }`

**Comment by erwstout** [comment]
This was an error based on the variable name in the ACF docs and the docs have been updated. Closing this issue since its not really an issue any longer. 

As @mattada shows, as long as the acf option page variable is not `$page` its fine. 

You can also setup pages with:

```php
// add option pages
if( function_exists('acf_add_options_page') ) {

	acf_add_options_page('Mega Menus');
	acf_add_options_page('Blog Intro Content');

}
```
