### ISSUE TITLE
In Depth Prelude Use with Wiki Pages 

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#59]
I have already begun to leverage the Wiki a bit to add more in depth info on functions but building out the wiki with better documentation other then the readme might be helpful. Thoughts? 

@bebaps @mattada

**Comment by mattada** [comment]
I think thats a good idea. I can help.

**Comment by bebaps** [comment]
I agree. That is what the Wiki is for, we have just never utilized it. We should document everything that we think might cause a person to question if they are using it correctly or not (functions, social menu, etc.)

The only thing we need to decide is if we'll keep all that documentation in the Wiki or also add comments  such as Docblocks for reference.

**Comment by erwstout** [comment]
I think I'd want to leave Docblocks out of it and just rely on the wiki, readme etc. I think it would offer a cleaner code base.
