### ISSUE TITLE
False Positive With Gulp Notify

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#60]
The new notify feature fires an error message "Error compiling JS" when simple Warnings are called. Is there a way to limit it only to Errors, or change the messaging based on if its just a Warning? 

![screen shot 2016-05-10 at 1 56 44 pm](https://cloud.githubusercontent.com/assets/9441913/15162313/102bc878-16b7-11e6-9c20-7a81ff8b8619.png)

In this example, it is a legitimate Warning, but in the past i've seen warnings that are irrelevant and it would be slightly annoying to get an "Error" when there actually aren't any.

**Comment by bebaps** [comment]
The Gulp Notify plugin simply alerts based upon the findings of the plugin(s) that it is attached to. In this case, JSHint is what is actually flagging this as a warning. If the `.jshintrc` file is still there, that is where you can specify what gets flagged or ignored. If there is no `.jshintrc`, then it is going off of the default plugin configuration.
