### ISSUE TITLE
Documentation for Users not installing from NPM

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#63]
Need to better support users who are not using npm to install prelude with documentation.

**Comment by erwstout** [comment]
Revisiting this, I don't think this is really applicable. A user needs to be using node/npm to run it anyway.... Feelings about closing this and moving on?

**Comment by mattada** [comment]
Im with you. The docs are pretty clear you need to be running node and NPM. If you dont know how then prelude is a rough fit to begin with.

**Comment by bebaps** [comment]
I am ambivalent. Yes, users need to read the documentation. But I should also be able to download a zip of the latest release and expect it to work just the same.

**Comment by erwstout** [comment]
Which, it would after running `npm install` - closing.
