### ISSUE TITLE
Thoughts on including normalize as a dependency?

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#66]
Lately Ive been adding `normalize-scss` to our projects since Ginger doesn't include a reset/normalize by default. Any thoughts on including this normalize package as a dependency already set up and ready to go? It would shave a little time off project setups... Thoughts?

@mattada @bebaps

**Comment by bebaps** [comment]
I already use it, in addition to sanitize.css so I am all for it

**Comment by erwstout** [comment]
Now on `release/3.3.0` branch
