### ISSUE TITLE
No support for SVG?

### ISSUE THREAD

**Issue by markbloomfield** [factor1/prelude-wp#78]
Was very keen to give this a go, but on looking through your `gulpfile.js`, I don't see any support for minification of SVG files?

Would be great if you would give this consideration?

**Comment by erwstout** [comment]
Hi Mark,

We use `gulp-imagemin` (https://github.com/sindresorhus/gulp-imagemin) for image compression, and it does have an option for compressing SVG's. You would just need to modify your task to include the option and you would be all set. Thanks!

**Comment by markbloomfield** [comment]
oh awesome, thanks! will give it a try

**Comment by erwstout** [comment]
With the rise of SVG it might be beneficial for us to include this by default, so I'll create a separate issue about making this default, or if you get it setup and working correctly feel free to do a PR as well. Thanks!

**Comment by erwstout** [comment]
Update! By default `gulp-imagemin` is using the svg plugin, so the disconnect here was just not including `svg` files in the `imageFiles` array, so on line 14 of `gulpfile.js` use this:

```js
    imageFiles   = ['./assets/img/*.{jpg,png,gif,svg}'],
```

And boom! Thanks for checking out Prelude, Mark. Would love to hear your feedback and thoughts once you get a chance to play around a bit more.
