### ISSUE TITLE
Time for an update?

### ISSUE THREAD

**Issue by bebaps** [factor1/prelude-wp#85]
Open this up for discussion. I have not been using Prelude much until recently when I started updating some older sites, or converting sites that we have taken over. When I was working on Hoover Printing in particular, a task was to update it and convert it to Prelude. When I was converting it I noticed that most of the theme was exactly the same. Matt mentioned that Hoover was one of the first themes he made with the Blank theme from Chris Coyier, and between that theme and the current Prelude not much has changed.

So I tried to look up the repo for the Blank theme, but there isn't one because of how old it is (almost 6 years old). I dug up the original blog post where Chris Coyier introduced Blank https://digwp.com/2010/02/blank-wordpress-theme/, which has an update from him where he recommends to use this theme instead http://html5reset.org/#wordpress because it is more up to date. However, following this page to the themes repo https://github.com/murtaugh/HTML5-Reset-Wordpress-Theme you can see that this also is old and has not been updated in years.

Then recently when I was including the translation functions for Ancora, I had the same thoughts. A much newer website with the same codebase as a site really old as far as web development goes.

Now clearly this really isn't a problem because the sites still function just fine as the are, but me being me, I can't help but wonder if the theme is keeping up with the changes of WordPress as well as it could. Each release of WordPress introduces new functions and deprecates others, and there might be some really useful stuff we just aren't taking advantage of simply because we aren't looking to do so.

We briefly talked about Underscores before and the summary was that we never used it because it had a lot of stuff we don't use, but I think it may be time to reconsider, especially when looking at the increase in complexity with the most recent themes we made, and just the other day Matt was excited to get to use (or consider to use) React in TechPinions I think it was, it seems like an eventuality that Prelude will need to be updated to better support these potential technologies out of the box.

Anyway, I downloaded a copy of Underscores https://github.com/Automattic/_s and looked it over, and I think that most of it we can benefit from. Of course we will tweak it to fit our needs, and those changes would probably be more along the lines of structural changes rather than actual code overhauls. The most important thing that stood out to me though is that it is developed and updated in parallel with WordPress core, so it will always make use of the most recent and most appropriate WordPress functions and follow the best practices for theme development (at least in the eyes of the WordPress folks). For example we commonly make use of an ACF options page to add titles to archive pages, when newer functions like `the_archive_title()` and `the_archive_description()` were introduced in WordPress 4.1.0 to do exactly that.

# Discussion:
In my opinion, we should consider updating Prelude to be based off of either Underscores or the HTML5 Reset theme (I think Sage is still far away from what we do, but if using React becomes a serious consideration in our themes then we should really consider that one too). The direction our themes appear to be moving, I don't see a reason why one of these two shouldn't be seriously considered.

Using Underscores would be more of an overhaul to Prelude as we know it, but probably better in the long run as it would force us to keep up with the new features of WordPress as they are released. Using the HTML5 Reset theme would be the more comfortable option, as it is already more aligned with the code Prelude uses just without the custom functionality we added along the way (which really isn't a great amount anyway).

I know that one major point of Prelude was to keep it open for anyone to use and not just us, but I am still of the mindset that Prelude should be for us first, and if anyone else wants to use it too then they are welcome to do so.

**Comment by erwstout** [comment]
I know we talked about this in office a bit but just wanted to document here for further reference.

- While we make WordPress themes, first and foremost we make custom _sites_ that use wordpress as a tool
- What functionality are we _missing_ that can be rolled in while keeping our starting point lean and mean 

I probably won't have much time to dive into these other frameworks/tools for comparisons so it would be beneficial to see examples of things we may be missing or could use in practice.

**Comment by erwstout** [comment]
Closing this just so its not sitting as an open task.
