### ISSUE TITLE
functions/tweaks hiding post author

### ISSUE THREAD

**Issue by mattada** [factor1/prelude-wp#87]
On line 80 of inc/tweaks.php we are hiding the post author meta box. I honestly dont know why we have this set that way, It's almost always an issue we need to remove for a site launch. 

I saw we leave the core author meta box in place, and only hide it if there is actually a need to hide it. 

`remove_meta_box( 'authordiv', 'post', 'normal' ); // Author Metabox`

**Comment by bebaps** [comment]
This has always been a part of your version of the Blank theme. You may have just copied it in without paying much attention to it.

Maybe this file should be review to see what makes sense to stay as a theme tweak and what should be extracted out to a custom plugin we use on our sites.

**Comment by mattada** [comment]
Ohh i know it came from the f1_blank fork all those years ago, just not sure why that was a good idea. I assume it was in an effort to simplify the interface for less advanced users.

**Comment by erwstout** [comment]
Updates with hotfix `3.3.12`
