### ISSUE TITLE
Proposal: Merge erwstout/sugar into prelude

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#91]
Since we all use rem's here in office to render font styles, would anyone be opposed to merging sugar into prelude? Honestly, everything that is in sugar is out of date and its only included into projects for the rem calcs... So why not just move rem calcs into prelude?

Thoughts?

That way you can just use something like:

```scss
h1{
  font-size: rem(32px);
}
```

Without any outside dependencies.

**Comment by mattada** [comment]
Yeah I'm fine with that. Once less dependancy.

**Comment by erwstout** [comment]
Correction, I would propose moving these mixins/functions into prelude from Sugar:

- rem
- aspect ratio mixin

**Comment by bebaps** [comment]
yea, I have my own I been using for rem, em, aspect ratio, etc. so it wont bother me

**Comment by mattada** [comment]
And by the hand of matt, i grant this idea approved and issue closed.
