### ISSUE TITLE
Delete CSS before compile

### ISSUE THREAD

**Issue by bebaps** [factor1/prelude-wp#93]
Have encountered times when Sass changes are not reflected in the compiled CSS at all. Example, I just had to edit 1 line of code in Stewart, then manually ran `gulp styles`. Refreshed the browser, no change. Inspect the element show the old CSS still. Deleting the CSS and then recompiling resolves this.

Should add a task to delete any compiled CSS files, and then compile Sass.

**Comment by erwstout** [comment]
Hmm, interesting. Is this in a staging environment _on_ a server? I've never experienced this unless the file wasn't in `theme.scss` before `gulp styles` was ran OR the only time I have seen this is when its on a staging server and clearing cache in browser fixes the issue. Curious about the environment. 

Have you done any modifications to the gulpfile at all?

**Comment by erwstout** [comment]
Keep this issue updated on if it happens after you reformat your machine this week.
