### ISSUE TITLE
Function Tweaks needs updated - get_currentuserinfo is deprecated

### ISSUE THREAD

**Issue by mattada** [factor1/prelude-wp#97]
/inc/tweaks.php 

`Notice: get_currentuserinfo is deprecated since version 4.5.0! Use wp_get_current_user() instead.
`
The bigger question. Is this even needed anymore? This is a 2011 artifact from when WP updates could break sites. We no longer have this fear with our code being ruined by an update.

**Comment by mattada** [comment]
/inc/tweaks.php     Lines 51 - 56

```
  get_currentuserinfo();

  if ( !current_user_can( 'update_plugins' ) ) {
    add_action('init', create_function( '$a', "remove_action( 'init', 'wp_version_check' );" ), 2);
    add_filter('pre_option_update_core', create_function( '$a', 'return null;' ) );
  }
```

**Comment by erwstout** [comment]
I think it can just be removed.

**Comment by erwstout** [comment]
Removed!
