### ISSUE TITLE
Use package.json to generate parts of the style.css header

### ISSUE THREAD

**Issue by cklosowski** [factor1/prelude-wp#99]
Since the data is being collected when setting up the theme, we could populate the header of the `style.css` file with some of the data we received on initial setup.

**Comment by erwstout** [comment]
Still been thinking/working on this. I'd have to run some tests, but something along the lines of:

`var data = require('some-module/package.json')` may work or possibly [this](https://github.com/npm/read-package-json).

**Comment by erwstout** [comment]
Added a new npm script `prelude-init` that will prompt users for theme info and replace it in `style.css` and `gulpfile.js`.

Will be rolled out with `release/4.0.0`.

**Comment by erwstout** [comment]
Delayed until `release/5.0.0` - this basically comes from finding out that the `npm script` will not be accessible from the new project install. Release 5.0.0 is already being planned to be a major change where Prelude will be installed globally via npm - and will generate a new project for the user. Timeline for 5.0.0 is unknown for now but given the urgency of 4.0.0 this is being pushed.

**Comment by erwstout** [comment]
Closing this for now. It may still be on the roadmap for a future `5.0.0` release should that happen.
